name: PR build
on:
  push:
    branches:
      - master
jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      # Step that runs the tests
      - name: Run tests
        run: mvn test
